const CUSTOMER_ELIGIBLE = "CUSTOMER_ELIGIBLE";
const CUSTOMER_INELIGIBLE = "CUSTOMER_INELIGIBLE";
const TECHNICAL_FAILURE = "TECHNICAL_FAILURE";
const INVALID_ACCOUNT_NUMBER = "INVALID_ACCOUNT_NUMBER";

const SPORTS = "SPORTS";
const KIDS = "KIDS";
const MUSIC = "MUSIC";
const NEWS = "NEWS";
const MOVIES = "MOVIES";

const CHAMPIONS_LEAGUE_FINAL_TICKET = "CHAMPIONS_LEAGUE_FINAL_TICKET";
const KARAOKE_PRO_MICROPHONE = "KARAOKE_PRO_MICROPHONE";
const PIRATES_OF_THE_CARRIBEAN_COLLECTION =
  "PIRATES_OF_THE_CARIBBEAN_COLLECTION";

const associatedRewards = {
  [SPORTS]: [CHAMPIONS_LEAGUE_FINAL_TICKET],
  [KIDS]: [],
  [MUSIC]: [KARAOKE_PRO_MICROPHONE],
  [NEWS]: [],
  [MOVIES]: [PIRATES_OF_THE_CARRIBEAN_COLLECTION],
};

module.exports = {
  CUSTOMER_ELIGIBLE,
  CUSTOMER_INELIGIBLE,
  TECHNICAL_FAILURE,
  INVALID_ACCOUNT_NUMBER,
  SPORTS,
  KIDS,
  MUSIC,
  NEWS,
  MOVIES,
  CHAMPIONS_LEAGUE_FINAL_TICKET,
  KARAOKE_PRO_MICROPHONE,
  PIRATES_OF_THE_CARRIBEAN_COLLECTION,
  associatedRewards,
};
